//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Formularios.FormsPrincipales {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class ConfigLicencias : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigLicencias defaultInstance = ((ConfigLicencias)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigLicencias())));
        
        public static ConfigLicencias Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8768684201930")]
        public string Licencia30Dias {
            get {
                return ((string)(this["Licencia30Dias"]));
            }
            set {
                this["Licencia30Dias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8768684201920")]
        public string Licencia20Dias {
            get {
                return ((string)(this["Licencia20Dias"]));
            }
            set {
                this["Licencia20Dias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8768684201910")]
        public string Licencia10Dias {
            get {
                return ((string)(this["Licencia10Dias"]));
            }
            set {
                this["Licencia10Dias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8768684201908")]
        public string Licencia8Dias {
            get {
                return ((string)(this["Licencia8Dias"]));
            }
            set {
                this["Licencia8Dias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("876868420192019")]
        public string LicenciaCompleta {
            get {
                return ((string)(this["LicenciaCompleta"]));
            }
            set {
                this["LicenciaCompleta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Licencia8Dias")]
        public string LicenciaActual {
            get {
                return ((string)(this["LicenciaActual"]));
            }
            set {
                this["LicenciaActual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConteoLicencia30 {
            get {
                return ((int)(this["ConteoLicencia30"]));
            }
            set {
                this["ConteoLicencia30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConteoLicencia20 {
            get {
                return ((int)(this["ConteoLicencia20"]));
            }
            set {
                this["ConteoLicencia20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConteoLicencia10 {
            get {
                return ((int)(this["ConteoLicencia10"]));
            }
            set {
                this["ConteoLicencia10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConteoLicencia8 {
            get {
                return ((int)(this["ConteoLicencia8"]));
            }
            set {
                this["ConteoLicencia8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2021-03-22")]
        public global::System.DateTime FechaConteo {
            get {
                return ((global::System.DateTime)(this["FechaConteo"]));
            }
            set {
                this["FechaConteo"] = value;
            }
        }
    }
}
